server:
  port: 8086

spring:
  application:
    name: report-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
  expiry: 86400000

springdoc:
  servers:
    - url: http://localhost:9900     # ✅ yeh sahi hai
