spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/evaluation_db
    username: postgres
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
